### ISSUE TITLE
Slow camera opening

### ISSUE THREAD

**Issue by giacomocastellucci** [ShyMemoriees/Rose#10]
iPhone X (GSM), iOS 13.3 - Rose 4.1

i had an issue with the camera opening, [this is the reddit post I made, it includes a video comparison and a tweak list](https://www.reddit.com/r/jailbreak/comments/ee5fub/discussion_camera_significantly_slower_with/). I tried disabling every tweak, one by one in iCleaner, to find the culprit. After disabling Rose, the camera started opening in a reasonable time again. I can't wrap my head around this, I really, really love this tweak and don't want to remove it. I hope this issue can get recognized and possibly fixed. Thanks for the hard work.

**Comment by ShyMemoriees** [comment]
Hiya 😊

This comment explains most of it, Rose has a big amount of code means not only your camera will open a few milliseconds later because of all the code which gets injected, if i find a way to solve it i’ll do it course 😊 https://www.reddit.com/r/jailbreak/comments/ee5fub/discussion_camera_significantly_slower_with/fbq5giz/?utm_source=share&utm_medium=ios_app&utm_name=iossmf

**Comment by giacomocastellucci** [comment]
thank you :)
